services:
  app:
    build:
      context: .
      dockerfile: dev-ops/Dockerfile
    env_file:
      - dev.env
    ports:
      - "5000:5000"
  backend:
    build:
      context: .
      dockerfile: dev-ops/Dockerfile.backend
    env_file:
      - dev.env
    ports:
      - "5000:5000"