import requests

TOOLS = [
    {
        "name": "Mobilize",
        "description": "Mobilize is¬†an event management and volunteer recruitment platform. It is specifically designed for nonprofits, labor unions, campaigns, committees, advocacy groups, and other mission-driven organizations.",
        "category_id": 1,
        "logo_url": "https://can2-prod.s3.amazonaws.com/uploads/data/001/034/355/original/screenshot_2025-08-28_at_11028-pm.png",
        "regular_price": "Variable",
        "member_price": "Pay Per Dashboard",
        "discount_percentage": 25,
        "is_featured": True,
        "tier_requirement": None,
        "rating": 4.7,
        "review_count": 10972,
        "created_at": "1/1/24",
        "updated_at": "8/25/25",
        "is_active": True,
    },
    {
        "name": "GetThru",
        "description": "Reach Your Supporters One-To-One. Send personalized text messages and have real conversations with your supporters, participants, and community members.",
        "category_id": 2,
        "logo_url": "https://can2-prod.s3.amazonaws.com/uploads/data/001/034/357/original/getthru.png",
        "regular_price": "Variable",
        "member_price": "Pay Per MMS, SMS, Dial",
        "discount_percentage": 30,
        "is_featured": True,
        "tier_requirement": None,
        "rating": 4.7,
        "review_count": 9284,
        "created_at": "1/1/24",
        "updated_at": "8/25/25",
        "is_active": True,
    },
    {
        "name": "Hex",
        "description": "Hex is the AI-powered analytics workspace built for teams driving faster answers and better decisions.",
        "category_id": 3,
        "logo_url": "https://can2-prod.s3.amazonaws.com/uploads/data/001/034/356/original/hex_purple_for_light_backgrounds.png",
        "regular_price": "$75.00",
        "member_price": "$50.00",
        "discount_percentage": 15,
        "is_featured": True,
        "tier_requirement": None,
        "rating": 4.5,
        "review_count": 7267,
        "created_at": "1/1/24",
        "updated_at": "8/25/25",
        "is_active": True,
    },
    {
        "name": "NewMode",
        "description": "New/Mode‚Äôs community engagement toolbox empowers supporters to shape key decisions. The tool box features include: one click email your representative, one click call your representative, tweet @yourrep, automated letters to the editor and one click fax your representative.",
        "category_id": 4,
        "logo_url": "https://can2-prod.s3.amazonaws.com/uploads/data/001/034/362/original/new_mode.png",
        "regular_price": "Variable",
        "member_price": "Variable",
        "discount_percentage": 10,
        "is_featured": False,
        "tier_requirement": None,
        "rating": 4.4,
        "review_count": 11236,
        "created_at": "1/1/24",
        "updated_at": "8/25/25",
        "is_active": True,
    },
    {
        "name": "TargetSmart",
        "description": "Targetsmart is a national voter file, updated monthly. This includes access within the Civis Platform to key fields from the analytics file, in addition to access to the Targetsmart ListBuilder where members can access all available models and fields.",
        "category_id": 5,
        "logo_url": "https://can2-prod.s3.amazonaws.com/uploads/data/001/034/361/original/targetsmart.png",
        "regular_price": "",
        "member_price": "",
        "discount_percentage": 25,
        "is_featured": False,
        "tier_requirement": None,
        "rating": 4.6,
        "review_count": 8343,
        "created_at": "1/1/24",
        "updated_at": "8/25/25",
        "is_active": True,
    },
    {
        "name": "Hustle",
        "description": "Hustle is a platform for both Broadcast and Peer-to-Peer texting.",
        "category_id": 6,
        "logo_url": "https://can2-prod.s3.amazonaws.com/uploads/data/001/034/365/original/hustle.png",
        "regular_price": "Variable",
        "member_price": "Pay Per Message",
        "discount_percentage": 40,
        "is_featured": False,
        "tier_requirement": None,
        "rating": 4.7,
        "review_count": 4573,
        "created_at": "1/1/24",
        "updated_at": "8/25/25",
        "is_active": True,
    },
    {
        "name": "Impactive",
        "description": "Impactive is a multipurpose organizing application that builds on the foundation of relational organizing.",
        "category_id": 7,
        "logo_url": "https://can2-prod.s3.amazonaws.com/uploads/data/001/034/364/original/impactive.png",
        "regular_price": "Variable",
        "member_price": "Variable",
        "discount_percentage": 50,
        "is_featured": False,
        "tier_requirement": None,
        "rating": 4.3,
        "review_count": 3978,
        "created_at": "1/1/24",
        "updated_at": "8/25/25",
        "is_active": True,
    },
    {
        "name": "Civis Analytics",
        "description": "Civis Platform is a data warehouse. Sync, store and manipulate data from many sources in one data warehouse. The database is pre-populated with the TargetSmart and Catalist national analytics files. Members have direct SQL access to their data and data science tools.",
        "category_id": 3,
        "logo_url": "https://can2-prod.s3.amazonaws.com/uploads/data/001/034/359/original/screenshot_2025-08-28_at_11452-pm.png",
        "regular_price": "$220.00",
        "member_price": "$110.00",
        "discount_percentage": 10,
        "is_featured": False,
        "tier_requirement": None,
        "rating": 4.5,
        "review_count": 6943,
        "created_at": "1/1/24",
        "updated_at": "8/25/25",
        "is_active": True,
    },
]

if __name__ == "__main__":
    for tool in TOOLS:
        r = requests.post("http://localhost:5000/api/tools/add", json=tool)
