"""add contact title

Revision ID: 069c3d39305e
Revises: 0afcdfad6fdb
Create Date: 2025-08-28 06:08:36.734425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069c3d39305e'
down_revision: Union[str, None] = '0afcdfad6fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_contacts', sa.Column('contact_title', sa.String(length=255), nullable=True), schema='tmc_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_contacts', 'contact_title', schema='tmc_dev')
    # ### end Alembic commands ###
