"""remove extra IDs

Revision ID: 0afcdfad6fdb
Revises: dad46a26f47e
Create Date: 2025-08-28 05:54:27.710719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afcdfad6fdb'
down_revision: Union[str, None] = 'dad46a26f47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_owners', 'id', schema='tmc_dev')
    op.drop_column('data_sharing', 'id', schema='tmc_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sharing', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"tmc_dev".data_sharing_id_seq\'::regclass)'), autoincrement=True, nullable=False), schema='tmc_dev')
    op.add_column('data_owners', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"tmc_dev".data_owners_id_seq\'::regclass)'), autoincrement=True, nullable=False), schema='tmc_dev')
    # ### end Alembic commands ###
