"""nullable updated at

Revision ID: 104167d246e2
Revises: 92e9dc75e17d
Create Date: 2025-08-27 05:33:14.668724

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "104167d246e2"
down_revision: Union[str, None] = "92e9dc75e17d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        schema="tmc_dev",
    )
    op.alter_column(
        "organization_contacts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        schema="tmc_dev",
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        schema="tmc_dev",
    )
    op.alter_column(
        "vendors",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        schema="tmc_dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vendors",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        schema="tmc_dev",
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        schema="tmc_dev",
    )
    op.alter_column(
        "organization_contacts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        schema="tmc_dev",
    )
    op.alter_column(
        "organization",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        schema="tmc_dev",
    )
    # ### end Alembic commands ###
