"""make pricing variable

Revision ID: 1cc95b83d993
Revises: 069c3d39305e
Create Date: 2025-08-28 13:09:12.595851

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1cc95b83d993'
down_revision: Union[str, None] = '069c3d39305e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'regular_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=False,
               schema='tmc_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'regular_price',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               schema='tmc_dev')
    # ### end Alembic commands ###
