"""update foreign key

Revision ID: 3501eade6094
Revises: 104167d246e2
Create Date: 2025-08-27 05:36:54.789493

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3501eade6094"
down_revision: Union[str, None] = "104167d246e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "data_owners_data_owner_id_fkey",
        "data_owners",
        schema="tmc_dev",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "data_owners",
        "organization",
        ["data_owner_id"],
        ["data_owner_id"],
        source_schema="tmc_dev",
        referent_schema="tmc_dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "data_owners", schema="tmc_dev", type_="foreignkey")
    op.create_foreign_key(
        "data_owners_data_owner_id_fkey",
        "data_owners",
        "organization",
        ["data_owner_id"],
        ["id"],
        source_schema="tmc_dev",
        referent_schema="tmc_dev",
    )
    # ### end Alembic commands ###
