"""supabase init

Revision ID: 4bf54195cd32
Revises: 290279159dca
Create Date: 2025-08-25 14:53:17.602246

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bf54195cd32"
down_revision: Union[str, None] = "290279159dca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("data_owner_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_type", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(), nullable=True),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("slack_channel", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_owner_id"),
        schema="tmc_dev",
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="tmc_dev",
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="tmc_dev",
    )
    op.create_table(
        "data_shares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("granting_data_owner_id", sa.Integer(), nullable=False),
        sa.Column("receiving_data_owner_id", sa.Integer(), nullable=False),
        sa.Column("grant_national", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granting_data_owner_id"],
            ["tmc_dev.organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiving_data_owner_id"],
            ["tmc_dev.organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tmc_dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_shares", schema="tmc_dev")
    op.drop_table("user", schema="tmc_dev")
    op.drop_table("role", schema="tmc_dev")
    op.drop_table("organization", schema="tmc_dev")
    # ### end Alembic commands ###
