"""make nullable

Revision ID: 66740ab7df86
Revises: 57c04388ef74
Create Date: 2025-08-28 13:39:06.038841

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66740ab7df86"
down_revision: Union[str, None] = "57c04388ef74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tools",
        "member_price",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "discount_percentage",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "is_featured",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "tier_requirement",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "rating",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "review_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="tmc_dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tools",
        "review_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "rating",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "tier_requirement",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "is_featured",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "discount_percentage",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        schema="tmc_dev",
    )
    op.alter_column(
        "tools",
        "member_price",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="tmc_dev",
    )
    # ### end Alembic commands ###
