"""add data sharing description

Revision ID: 6f631b627766
Revises: 3501eade6094
Create Date: 2025-08-27 05:51:26.357680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f631b627766'
down_revision: Union[str, None] = '3501eade6094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sharing', sa.Column('description', sa.String(length=255), nullable=True), schema='tmc_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sharing', 'description', schema='tmc_dev')
    # ### end Alembic commands ###
