"""dev init

Revision ID: 92e9dc75e17d
Revises:
Create Date: 2025-08-27 05:21:09.882451

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92e9dc75e17d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_owners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data_owner_id", sa.Integer(), nullable=False),
        sa.Column("data_owner_code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_owner_id"],
            ["tmc_dev.organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_owner_code"),
        sa.UniqueConstraint("data_owner_id"),
        schema="tmc_dev",
    )
    op.add_column(
        "organization",
        sa.Column("google_group_name", sa.String(length=255), nullable=True),
        schema="tmc_dev",
    )
    op.add_column(
        "organization",
        sa.Column("haven_project_name", sa.String(length=255), nullable=True),
        schema="tmc_dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "haven_project_name", schema="tmc_dev")
    op.drop_column("organization", "google_group_name", schema="tmc_dev")
    op.drop_table("data_owners", schema="tmc_dev")
    # ### end Alembic commands ###
