"""kill fk with vendors

Revision ID: aeca0658c707
Revises: 66740ab7df86
Create Date: 2025-08-28 13:40:35.293246

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aeca0658c707'
down_revision: Union[str, None] = '66740ab7df86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tools_vendor_id_fkey', 'tools', schema='tmc_dev', type_='foreignkey')
    op.drop_column('tools', 'vendor_id', schema='tmc_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='tmc_dev')
    op.create_foreign_key('tools_vendor_id_fkey', 'tools', 'vendors', ['vendor_id'], ['id'], source_schema='tmc_dev', referent_schema='tmc_dev')
    # ### end Alembic commands ###
