"""init with metadata

Revision ID: c252d1e3adfa
Revises: 
Create Date: 2025-08-26 14:40:39.695249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c252d1e3adfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_owner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_type', sa.String(length=100), nullable=False),
    sa.Column('organization_size', sa.String(length=100), nullable=True),
    sa.Column('member_tier', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('slack_channel', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_owner_id'),
    schema='tmc_dev'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tmc_dev'
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    op.create_table('tool_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('tool_count', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    op.create_table('tool_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=False),
    sa.Column('partnership_tier', sa.Integer(), nullable=False),
    sa.Column('tool_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    op.create_table('data_sharing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('granting_data_owner_id', sa.Integer(), nullable=False),
    sa.Column('receiving_data_owner_id', sa.Integer(), nullable=False),
    sa.Column('grant_national', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granting_data_owner_id'], ['tmc_dev.organization.data_owner_id'], ),
    sa.ForeignKeyConstraint(['receiving_data_owner_id'], ['tmc_dev.organization.data_owner_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    op.create_table('organization_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['tmc_dev.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    op.create_table('organization_tags',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['tmc_dev.organization.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tmc_dev.tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id'),
    schema='tmc_dev'
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=False),
    sa.Column('regular_price', sa.Float(), nullable=False),
    sa.Column('member_price', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('tier_requirement', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tmc_dev.tool_categories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['tmc_dev.vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['tmc_dev.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='tmc_dev'
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['tmc_dev.organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tmc_dev.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tmc_dev.role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tmc_dev.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('subscription_length', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['tmc_dev.orders.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tmc_dev.tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tmc_dev'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items', schema='tmc_dev')
    op.drop_table('user_roles', schema='tmc_dev')
    op.drop_table('orders', schema='tmc_dev')
    op.drop_table('user', schema='tmc_dev')
    op.drop_table('tools', schema='tmc_dev')
    op.drop_table('organization_tags', schema='tmc_dev')
    op.drop_table('organization_contacts', schema='tmc_dev')
    op.drop_table('data_sharing', schema='tmc_dev')
    op.drop_table('vendors', schema='tmc_dev')
    op.drop_table('tool_tags', schema='tmc_dev')
    op.drop_table('tool_categories', schema='tmc_dev')
    op.drop_table('tags', schema='tmc_dev')
    op.drop_table('role', schema='tmc_dev')
    op.drop_table('organization', schema='tmc_dev')
    # ### end Alembic commands ###
