"""add username

Revision ID: c37c8e847cf2
Revises: 6f631b627766
Create Date: 2025-08-27 06:05:41.158177

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c37c8e847cf2"
down_revision: Union[str, None] = "6f631b627766"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("name", sa.String(length=255), nullable=False),
        schema="tmc_dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "name", schema="tmc_dev")
    # ### end Alembic commands ###
