"""join date required

Revision ID: dad46a26f47e
Revises: e0322d2896e5
Create Date: 2025-08-27 14:48:26.228745

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dad46a26f47e'
down_revision: Union[str, None] = 'e0322d2896e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'join_date',
               existing_type=sa.DATE(),
               nullable=False,
               schema='tmc_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'join_date',
               existing_type=sa.DATE(),
               nullable=True,
               schema='tmc_dev')
    # ### end Alembic commands ###
