"""add org columns

Revision ID: e0322d2896e5
Revises: ebfc32f7b707
Create Date: 2025-08-27 13:45:54.040764

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0322d2896e5"
down_revision: Union[str, None] = "ebfc32f7b707"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("join_date", sa.Date(), nullable=True),
        schema="tmc_dev",
    )
    op.add_column(
        "organization",
        sa.Column("location", sa.String(length=100), nullable=True),
        schema="tmc_dev",
    )
    op.add_column(
        "organization",
        sa.Column("logo", sa.String(length=255), nullable=True),
        schema="tmc_dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "logo", schema="tmc_dev")
    op.drop_column("organization", "location", schema="tmc_dev")
    op.drop_column("organization", "join_date", schema="tmc_dev")
    # ### end Alembic commands ###
