"""test in prod

Revision ID: ebfc32f7b707
Revises: 
Create Date: 2025-08-27 08:21:16.208883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebfc32f7b707'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_owners_data_owner_id_fkey', 'data_owners', schema='tmc_dev', type_='foreignkey')
    op.create_foreign_key(None, 'data_owners', 'organization', ['data_owner_id'], ['data_owner_id'], source_schema='tmc_dev', referent_schema='tmc_dev')
    op.add_column('data_sharing', sa.Column('description', sa.String(length=255), nullable=True), schema='tmc_dev')
    op.alter_column('organization', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='tmc_dev')
    op.alter_column('organization_contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='tmc_dev')
    op.alter_column('tools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='tmc_dev')
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=False), schema='tmc_dev')
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='tmc_dev')
    op.alter_column('vendors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='tmc_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='tmc_dev')
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='tmc_dev')
    op.drop_column('user', 'name', schema='tmc_dev')
    op.alter_column('tools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='tmc_dev')
    op.alter_column('organization_contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='tmc_dev')
    op.alter_column('organization', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='tmc_dev')
    op.drop_column('data_sharing', 'description', schema='tmc_dev')
    op.drop_constraint(None, 'data_owners', schema='tmc_dev', type_='foreignkey')
    op.create_foreign_key('data_owners_data_owner_id_fkey', 'data_owners', 'organization', ['data_owner_id'], ['id'], source_schema='tmc_dev', referent_schema='tmc_dev')
    # ### end Alembic commands ###
